apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: mysql
  labels:
    app: mysql-slave
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: mysql-slave
  clusterIP: None  # Headless Service
