# 复制配置 Job - 在 Master 和 Slave 都就绪后执行
# 用于在 Master 上创建复制用户，并配置 Slave 连接 Master
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-replication-setup
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ttlSecondsAfterFinished: 86400  # 完成后保留 24 小时便于查看日志
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: replication-setup
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Waiting for MySQL Master to be ready..."
              until mysql -h mysql-master.mysql.svc.cluster.local -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1" &>/dev/null; do
                echo "Master not ready, waiting..."
                sleep 5
              done
              
              echo "Creating replication user on Master..."
              mysql -h mysql-master.mysql.svc.cluster.local -u root -p${MYSQL_ROOT_PASSWORD} -e "
                CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_REPLICATION_PASSWORD}';
                GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
                FLUSH PRIVILEGES;
              "
              
              echo "Getting Master status..."
              MASTER_STATUS=$(mysql -h mysql-master.mysql.svc.cluster.local -u root -p${MYSQL_ROOT_PASSWORD} -e "SHOW MASTER STATUS\G")
              MASTER_LOG_FILE=$(echo "$MASTER_STATUS" | grep "File:" | awk '{print $2}')
              MASTER_LOG_POS=$(echo "$MASTER_STATUS" | grep "Position:" | awk '{print $2}')
              
              echo "Master Log File: $MASTER_LOG_FILE, Position: $MASTER_LOG_POS"
              
              echo "Waiting for MySQL Slave to be ready..."
              until mysql -h mysql-slave.mysql.svc.cluster.local -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1" &>/dev/null; do
                echo "Slave not ready, waiting..."
                sleep 5
              done
              
              echo "Configuring Slave replication..."
              mysql -h mysql-slave.mysql.svc.cluster.local -u root -p${MYSQL_ROOT_PASSWORD} -e "
                STOP SLAVE;
                RESET SLAVE ALL;
                CHANGE MASTER TO
                  MASTER_HOST='mysql-master.mysql.svc.cluster.local',
                  MASTER_USER='repl',
                  MASTER_PASSWORD='${MYSQL_REPLICATION_PASSWORD}',
                  MASTER_LOG_FILE='${MASTER_LOG_FILE}',
                  MASTER_LOG_POS=${MASTER_LOG_POS},
                  MASTER_AUTO_POSITION=0;
                START SLAVE;
              "
              
              echo "Verifying replication status..."
              mysql -h mysql-slave.mysql.svc.cluster.local -u root -p${MYSQL_ROOT_PASSWORD} -e "SHOW SLAVE STATUS\G"
              
              echo "Replication setup completed successfully!"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICATION_PASSWORD
