apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  # 请修改为您的实际密码，建议使用 base64 编码后放入 data 字段
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_REPLICATION_PASSWORD: "123456"
